# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr1 = np.arange(10)
print(arr1)
arr1.reshape(2, 5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr2 = np.arange(10).reshape(2, 5)
arr3 = np.ones((2, 5), dtype=np.int32)
np.vstack((arr2, arr3))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
np.hstack((arr2, arr3))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr4 = np.arange(10).reshape(2, 5)
print('Before:', arr4)
arr4 = arr4.flatten()
print('After:', arr4)

Before: [[0 1 2 3 4]
 [5 6 7 8 9]]
After: [0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr5 = np.arange(15).reshape(3, 5)
print(arr5)
arr5 = arr5.flatten()
arr5

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr6 = np.arange(15)
print(arr6)
arr6 = arr6.reshape(3, 5)
arr6

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr7 = np.arange(25).reshape(5, 5)
print(arr7)
np.square(arr7)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr8 = np.arange(30).reshape(5, 6)
print(arr8)
print('Mean:', np.mean(arr8))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean: 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
print('Standard Deviation:', np.std(arr8))

Standard Deviation: 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [10]:
print('Median:', np.median(arr8))

Median: 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
print('Transpose')
arr8.T

Transpose


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr12 = np.random.permutation(np.arange(16)).reshape(4, 4)
print(arr12)
print('Sum of Diagonal Elements:', arr12.trace())

[[ 3  0  8  2]
 [11  1  7 14]
 [ 9  6 12  4]
 [ 5 15 13 10]]
Sum of Diagonal Elements: 26


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
print('Determinent:', np.linalg.det(arr12))

Determinent: 8008.000000000001


## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
arr14 = np.arange(11)
print(arr14)
print('5th Percentile:', np.percentile(arr14, 5))
print('95th Percentile:', np.percentile(arr14, 95))

[ 0  1  2  3  4  5  6  7  8  9 10]
5th Percentile: 0.5
95th Percentile: 9.5


## Question:15

### How to find if a given array has any null values?

In [15]:
arr15 = np.array([12, -2, 5, -7, 1, 0, 15, 0])
arr15.all()

False